name: Pull request analysis

on:
  pull_request:
    branches:
    - master
    - feature/*
    
jobs:
  analysis:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with: 
        ref: ${{ github.ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install sonnarscanner
      run: |
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 2.1 --install-dir /opt/hostedtoolcache/dncs
        echo ::add-path::/opt/hostedtoolcache/dncs/2.1.802/x64
        dotnet tool install --tool-path /opt/hostedtoolcache/dncs/2.1.802/x64 dotnet-sonarscanner
    - name: Start SonarScanner
      run: dotnet sonarscanner begin /d:sonar.login=f48b8638f99cb3b259282e5facbeed33a4abf6b2 /k:VictorSilvaOliveira_webapplication /o:victorsilvaoliveira /d:sonar.host.url=https://sonarcloud.io /d:sonar.pullrequest.key=${{ github.head_ref }} /d:sonar.pullrequest.branch=${{ github.ref }} /d:sonar.pullrequest.base=master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Solution
      run: dotnet build WebApplication1.sln
    - name: End SonarScanner
      run: dotnet sonarscanner end /d:sonar.login=f48b8638f99cb3b259282e5facbeed33a4abf6b2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
